language: node_js
node_js:
  - "12"
cache: yarn
jobs:
  include:
    - stage: Test
      script: yarn test:lint
    - before_script: yarn global add codecov
      script: yarn test:ci
      after_success: codecov
    - stage: Deploy
      script: yarn build
env:
  global:
    - REPO="git@github.com:cdcabrera/t2"
    - AUTO_DEPLOY=true
    - AUTO_REBASE="stage,qa,ci,fake"
    - BRANCH="master"
    - EMAIL="cabrera.code@gmail.com"
    - USER="T2 CI"
