name: Commit lint
on:
  pull_request

jobs:
  Commits:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git commits
        run: |
          git remote add ssh-origin "https://github.com/$GITHUB_REPOSITORY"
          git fetch ssh-origin
          COMMITS=$(git cherry -v ssh-origin/master | grep "+")
          echo ::set-env name=GIT_COMMITS::$COMMITS
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint commits
        run: |
          RESULTS=$(node ./scripts/actions.commit.js "$GIT_COMMITS")
          echo ::set-env name=LINT_RESULTS::$RESULTS
      - name: Confirm
        if: ${{ failure() }}
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.actor,
              repo: context.repo.repo,
              body: `<!--commitlint-->\n### Commit lint\n${process.env.LINT_RESULTS}`
            })
