name: Commit lint
on:
  pull_request

jobs:
  Commits:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git commits
        run: |
          git remote add ssh-origin "https://github.com/$GITHUB_REPOSITORY"
          git fetch ssh-origin
          COMMITS=$(git cherry -v ssh-origin/master | grep "+")
          echo ::set-env name=GIT_COMMITS::$COMMITS
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint
        uses: actions/github-script@v2
        id: lint-result
        with:
          result-encoding: string
          script: |
            const actionCommit = require(`${process.env.GITHUB_WORKSPACE}/scripts/actions.commit.js`)
            const { resultsArray, resultsString } = actionCommit(process.env.GIT_COMMITS)

            if (resultsArray.length) {
              core.error(resultsString)
              return resultsString;
            }

            return ''
      - name: Set lint artifact
        if: ${{steps.lint-result.outputs.result != '' }}
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          echo -e '${{steps.lint-result.outputs.result}}' > ${{ github.workspace }}/artifact/commit_lint.txt
      - name: Lint failure
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: lint-failure ${{ matrix.node-version }}
          path: ${{ github.workspace }}/artifact/**/*
