name: Master Release
on:
  push:
    branches: [ master ]
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Checking last commit
        run: |
          git switch -c master
          echo ::set-env name=LAST_COMMIT::$(git log -1 --oneline)
          echo $LAST_COMMIT
      - name: Setup GIT
        if:  ${{ !startsWith( env.LAST_COMMIT, 'chore(' )  }}
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
      - name: Setup Node.js ${{ matrix.node-version }}
        if: ${{ success() }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run release
        if: ${{ success() }}
        run: |
          yarn install
          yarn release
      - name: Push release
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git push --follow-tags "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
