name: Pull request
on:
  pull_request:
    branches: [ master, prod, stage, qa**, ci** ]
env:
  BRANCH: ${{ github.base_ref }}

jobs:
  Integration-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node.js packages
        run: yarn install
      - name: Lint and test
        run: |
          TESTS=$(yarn test)
          echo ::set-env name=TEST_RESULTS::$TESTS
      - name: Set lint and test artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          echo -e $TEST_RESULTS > ${{ github.workspace }}/artifact/lint_test.txt
      - name: Code coverage
        if: ${{ success() }}
        uses: codecov/codecov-action@v1
      - name: Confirm beta integration
        if: ${{ success() }}
        run: |
          BETA_BUILD=$(yarn build)
          echo ::set-env name=BETA_BUILD_RESULTS::$BETA_BUILD
        env:
          BUILD_STAGE: Beta
      - name: Set beta integration artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          echo -e $BETA_BUILD_RESULTS > ${{ github.workspace }}/artifact/beta_build.txt
      - name: Confirm stable integration
        if: ${{ success() }}
        run: |
          STABLE_BUILD=$(yarn build)
          echo ::set-env name=STABLE_BUILD_RESULTS::$STABLE_BUILD
        env:
          BUILD_STAGE: Stable
      - name: Set stable integration artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          echo -e $STABLE_BUILD_RESULTS > ${{ github.workspace }}/artifact/stable_build.txt
      - name: Set artifacts
        uses: actions/upload-artifact@v2
        with:
          name: commit-lint-failure ${{ matrix.node-version }}
          path: ${{ github.workspace }}/artifact/**/*
