name: Pull request
on:
  pull_request:
    branches: [ master, prod, stage, qa**, ci** ]

jobs:
  Integration-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node.js packages
        run: yarn install
      - name: Set lint and test results script
        uses: actions/github-script@v2
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              console.log(`${execSync('yarn test')}`);
            } catch (error) {
              core.setFailed(`${error.stdout}\n${error.stderr}`);
            }
      - name: Code coverage
        if: ${{ success() }}
        uses: codecov/codecov-action@v1
      - name: Confirm beta integration
        if: ${{ success() }}
        uses: actions/github-script@v2
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              console.log(`${execSync('yarn build')}`);
            } catch (error) {
              core.setFailed(`${error.stdout}\n${error.stderr}`);
            }
        env:
          BUILD_STAGE: Beta
      - name: Confirm stable integration
        if: ${{ success() }}
        uses: actions/github-script@v2
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              console.log(`${execSync('yarn build')}`);
            } catch (error) {
              core.setFailed(`${error.stdout}\n${error.stderr}`);
            }
          env:
          BUILD_STAGE: Stable
