name: Pull request
on:
  pull_request:
    branches: [ master, prod, stage, qa**, ci** ]

jobs:
  Integration-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node.js packages
        run: yarn install
      - name: Clean artifacts
        run: |
          rm -rf ${{ github.workspace }}/artifact
      - name: Lint and test 1
        run: |
          LINT_TEST=$(yarn test 2>&1);
          if [ ! -z $("$LINT_TEST" | grep "exit code 1")  ]; then
            echo ::set-env name=LINT_TEST_ERROR::$LINT_TEST
          fi
      - name: Set lint and test 1a
        if: ${{ failure() && env.LINT_TEST_ERROR != '' }}
        uses: actions/github-script@v2
        with:
          script: |
            core.setFailed(process.env.LINT_TEST_ERROR)
      - name: Set lint and test 1b
        if: ${{ failure() }}
        uses: actions/github-script@v2
        with:
          script: |
            if (process.env.LINT_TEST_ERROR) {
              core.setFailed(process.env.LINT_TEST_ERROR)
            }
      - name: Lint and test 2
        if: ${{ always() }}
        uses: actions/github-script@v2
        with:
          result-encoding: string
          script: |
            const { execSync } = require('child_process')

            try {
              console.log(execSync('yarn test'))
            } catch (error) {
              core.setFailed(error.message)
            }
      - name: Lint and test artifact
        if: ${{ always() }}
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          yarn test |& tee ${{ github.workspace }}/artifact/lint_test.txt
      - name: Code coverage
        if: ${{ success() }}
        uses: codecov/codecov-action@v1
      - name: Confirm beta integration
        if: ${{ success() }}
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          yarn build > ${{ github.workspace }}/artifact/beta_build.txt
        env:
          BUILD_STAGE: Beta
      - name: Confirm stable integration
        if: ${{ success() }}
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          yarn build > ${{ github.workspace }}/artifact/stable_build.txt
        env:
          BUILD_STAGE: Stable
      - name: Set artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: pull-request ${{ matrix.node-version }}
          path: ${{ github.workspace }}/artifact/**/*
